#!/bin/bash

#SBATCH --nodes 1
#SBATCH --ntasks-per-node 4
#SBATCH --partition veryshort
#SBATCH --reservation COMS30005
#SBATCH --account COMS30005
#SBATCH --job-name MPI
#SBATCH --time 00:15:00
#SBATCH --output OUT
#SBATCH --exclusive

# This time, asking for 1 node with 4 tasks per node (to keep the runtime down)

# Use Intel MPI (make sure you compile with the same module and 'mpiicc')
module load languages/intel/2018-u3


# Print some information about the job
echo "Running on host $(hostname)"
echo "Time is $(date)"
echo "Directory is $(pwd)"
echo "Slurm job ID is $SLURM_JOB_ID"
echo
echo "This job runs on the following machines:"
echo "$SLURM_JOB_NODELIST" | uniq
echo


# Enable using `srun` with Intel MPI
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so

# Run the parallel MPI executable
echo "Running blocking.exe"
srun ./blocking.exe

echo
echo "Running non-blocking.exe"
srun ./non-blocking.exe

echo
echo "Running bugged-non-blocking.exe"
srun ./bugged-non-blocking.exe

