#!/bin/bash

#PBS -N MPI
#PBS -o OUT
#PBS -j oe
#PBS -q teaching
#PBS -l nodes=1:ppn=16,walltime=00:05:00

# Exit if any subsequent command fails
set -eu

# Use Intel MPI (make sure you compile with the same module and 'mpiicc')
module load languages/intel-compiler-16-u2

# Change to the working directory (default is home directory)
cd "$PBS_O_WORKDIR"

# Print some information about the job
echo "Running on host: $(hostname)"
echo "Time is: $(date)"
echo "Directory is: $(pwd)"
echo "PBS job ID is: $PBS_JOBID"
echo

# We request a full node but set the number of processes manually to avoid other jobs
# running on the same node at the same time
processes=4
nodes=$(uniq <"$PBS_NODEFILE")
echo "This jobs runs on the following machines: $(echo "$nodes" | tr '\n' ' ')"
echo "$(echo "$nodes" | wc -l) nodes, $processes processes"
echo

# Run the parallel MPI executable
mpirun -np "$processes" ./hello_world_c++.exe
