#!/bin/bash

#SBATCH --nodes 1
#SBATCH --ntasks-per-node 28
#SBATCH --partition veryshort
#SBATCH --reservation COMS30005
#SBATCH --account COMS30005
#SBATCH --job-name MPI
#SBATCH --time 00:15:00
#SBATCH --output OUT
#SBATCH --exclusive

# This time, asking for 1 node with 28 tasks per node

# Use Intel MPI (make sure you compile with the same module and 'mpiicc')
module load languages/intel/2018-u3


# Print some information about the job
echo "Running on host $(hostname)"
echo "Time is $(date)"
echo "Directory is $(pwd)"
echo "Slurm job ID is $SLURM_JOB_ID"
echo
echo "This job runs on the following machines:"
echo "$SLURM_JOB_NODELIST" | uniq
echo


# Enable using `srun` with Intel MPI
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so

# Run the parallel MPI executable
echo
echo "Running cartesian.exe"
srun ./cartesian.exe

echo
echo "Running neighbor_alltoall.exe"
srun ./neighbor_alltoall.exe

