#!/bin/bash

#PBS -N OpenMP
#PBS -j oe
#PBS -o OUT
#PBS -q teaching
#PBS -l nodes=1:ppn=16,walltime=00:05:00

# Exit if any subsequent command fails
set -eu

# Full path to application + application name
application="./hello_c.exe"

# Run options for the application
options=""

###############################################################
### You should not have to change anything below this line ####
###############################################################

# Change the working directory (default is home directory)
cd "$PBS_O_WORKDIR"

echo "Running on host: $(hostname)"
echo "Time is: $(date)"
echo "Directory is: $(pwd)"
echo "PBS job ID is: $PBS_JOBID"
echo "This jobs runs on the following machines: $(cat "$PBS_NODEFILE" | uniq)"

export OMP_NUM_THREADS=4
echo "Running $OMP_NUM_THREADS threads"
echo

#! Run the executable
time $application $options

